
#
/system/framework/framework.jar
#
/system/framework/framework.jar
6
(/system/framework/framework-graphics.jarTiramisu
6
(/system/framework/framework-graphics.jarTiramisu

/system/framework/ext.jar

/system/framework/ext.jar
*
&/system/framework/telephony-common.jar
*
&/system/framework/telephony-common.jar
%
!/system/framework/voip-common.jar
%
!/system/framework/voip-common.jar
$
 /system/framework/ims-common.jar
$
 /system/framework/ims-common.jar
(
$/system/framework/vivo-framework.jar
(
$/system/framework/vivo-framework.jar
$
 /system/framework/vivo-media.jar
$
 /system/framework/vivo-media.jar
+
'/system/framework/framework-adapter.jar
+
'/system/framework/framework-adapter.jar
'
#/system/framework/soc-framework.jar
'
#/system/framework/soc-framework.jar
(
$/system/framework/vivo-vgcclient.jar
(
$/system/framework/vivo-vgcclient.jar
)
%/system/framework/mediatek-common.jar
)
%/system/framework/mediatek-common.jar
,
(/system/framework/mediatek-framework.jar
,
(/system/framework/mediatek-framework.jar
+
'/system/framework/mediatek-ims-base.jar
+
'/system/framework/mediatek-ims-base.jar
1
-/system/framework/mediatek-telecom-common.jar
1
-/system/framework/mediatek-telecom-common.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar